name: 2-Build-and-Deploy

on:
  workflow_dispatch:  # 手動実行用

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PREFIX: api-3000-ssm-04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: 503561449641.dkr.ecr.ap-northeast-1.amazonaws.com
          ECR_REPOSITORY: ecr-api-3000
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd ./ecr-api-3000
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster ${PREFIX}-cluster --service ${PREFIX}-service --force-new-deployment

      - name: Monitor ECS deployment
        run: |
          aws ecs wait services-stable --cluster ${PREFIX}-cluster --services ${PREFIX}-service
          echo "Deployment completed successfully!"